apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: vallegrande
spec:
  type: NodePort
  selector:
    app: microservicio
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
