apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: vallegrande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: microservicio
          image: projecthackatom/microservicio:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
